replicaCount: 2 

image:
  repository: santhan29/sample-app 
  tag: "4ad21fc"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: sample-app.local
      paths:
        - path: /
          pathType: Prefix 